import { ApiOperation } from '@nestjs/swagger';
import { Controller, Get, Injectable, Module, Query } from '@nestjs/common';

type Locale = 'en'|'es'|'de'|'fr'|'it'|'pt'|'nl'|'pl'|'sv'|'da'|'fi'|'el'|'cs'|'ro'|'hu'|'ca'|'ru'|'ar'|'ko'|'zh'|'ja';

const T: Record<string, Record<string, string>> = {
  'risk.unacceptable': { en:'Unacceptable',es:'Inaceptable',de:'Inakzeptabel',fr:'Inacceptable',it:'Inaccettabile',pt:'Inaceitavel',nl:'Onaanvaardbaar',pl:'Niedopuszczalne',sv:'Oacceptabel',da:'Uacceptabel',fi:'Ei-hyvaksyttava',el:'Apardekto',cs:'Neprijatelne',ro:'Inacceptabil',hu:'Elfogadhatatlan',ca:'Inacceptable',ru:'Nedopustimyj',ar:'Ghyr maqbul',ko:'Heoyonghal su eopsneun',zh:'Buke jieshou',ja:'Kyoyou dekinai' },
  'risk.high': { en:'High',es:'Alto',de:'Hoch',fr:'Eleve',it:'Alto',pt:'Alto',nl:'Hoog',pl:'Wysokie',sv:'Hog',da:'Hoj',fi:'Korkea',el:'Ypsilo',cs:'Vysoke',ro:'Ridicat',hu:'Magas',ca:'Alt',ru:'Vysokij',ar:'Ali',ko:'Nopda',zh:'Gao',ja:'Takai' },
  'risk.limited': { en:'Limited',es:'Limitado',de:'Begrenzt',fr:'Limite',it:'Limitato',pt:'Limitado',nl:'Beperkt',pl:'Ograniczone',sv:'Begransat',da:'Begraenset',fi:'Rajoitettu',el:'Periorismeno',cs:'Omezene',ro:'Limitat',hu:'Korlitozott',ca:'Limitat',ru:'Ogranichennyj',ar:'Mahdud',ko:'Jehanjeog',zh:'Youxian',ja:'Gentei' },
  'risk.minimal': { en:'Minimal',es:'Minimo',de:'Minimal',fr:'Minimal',it:'Minimo',pt:'Minimo',nl:'Minimaal',pl:'Minimalne',sv:'Minimalt',da:'Minimalt',fi:'Minimaalinen',el:'Elachisto',cs:'Minimalni',ro:'Minim',hu:'Minimalis',ca:'Minim',ru:'Minimalnyj',ar:'Adna',ko:'Choesoneui',zh:'Zuixiao',ja:'Saishou' },
  'compliance.compliant': { en:'Compliant',es:'Cumple',de:'Konform',fr:'Conforme',it:'Conforme',pt:'Conforme',nl:'Conform',pl:'Zgodne',sv:'Overensstammande',da:'Overensstemmende',fi:'Vaatimustenmukainen',el:'Symmetocho',cs:'V souladu',ro:'Conform',hu:'Megfelelo',ca:'Conforme',ru:'Sootvetstvujushchij',ar:'Mutawafiq',ko:'Junsu',zh:'Heguide',ja:'Junshuu' },
  'compliance.partial': { en:'Partial',es:'Parcial',de:'Teilweise',fr:'Partiel',it:'Parziale',pt:'Parcial',nl:'Gedeeltelijk',pl:'Czesciowe',sv:'Delvis',da:'Delvis',fi:'Osittainen',el:'Meriko',cs:'Castecne',ro:'Partial',hu:'Reszleges',ca:'Parcial',ru:'Chastichnyj',ar:'Juz\'i',ko:'Bubun',zh:'Bufen',ja:'Bubun' },
  'compliance.non_compliant': { en:'Non-Compliant',es:'No cumple',de:'Nicht konform',fr:'Non conforme',it:'Non conforme',pt:'Nao conforme',nl:'Niet-conform',pl:'Niezgodne',sv:'Ej overensstammande',da:'Ikke overensstemmende',fi:'Vaatimustenvastaine',el:'Mi symmetocho',cs:'Nevyhovujici',ro:'Neconform',hu:'Nem megfelelo',ca:'No conforme',ru:'Nesootvetstvujushchij',ar:'Ghyr mutawafiq',ko:'Bujunsu',zh:'Bu heguide',ja:'Fujunshuu' },
  'severity.critical': { en:'Critical',es:'Critico',de:'Kritisch',fr:'Critique',it:'Critico',pt:'Critico',nl:'Kritiek',pl:'Krytyczne',sv:'Kritisk',da:'Kritisk',fi:'Kriittinen',el:'Krisimo',cs:'Kriticke',ro:'Critic',hu:'Kritikus',ca:'Critic',ru:'Kriticheskij',ar:'Harej',ko:'Chimyeongjeogin',zh:'Yanzhong',ja:'Jyuudai' },
  'severity.high': { en:'High',es:'Alto',de:'Hoch',fr:'Eleve',it:'Alto',pt:'Alto',nl:'Hoog',pl:'Wysokie',sv:'Hog',da:'Hoj',fi:'Korkea',el:'Ypsilo',cs:'Vysoke',ro:'Ridicat',hu:'Magas',ca:'Alt',ru:'Vysokij',ar:'Ali',ko:'Nopda',zh:'Gao',ja:'Takai' },
  'severity.medium': { en:'Medium',es:'Medio',de:'Mittel',fr:'Moyen',it:'Medio',pt:'Medio',nl:'Gemiddeld',pl:'Srednie',sv:'Medel',da:'Mellem',fi:'Keskitaso',el:'Mesaio',cs:'Stredni',ro:'Mediu',hu:'Kozepes',ca:'Mitja',ru:'Srednij',ar:'Mutawassit',ko:'Jung',zh:'Zhong',ja:'Chuukan' },
  'severity.low': { en:'Low',es:'Bajo',de:'Niedrig',fr:'Faible',it:'Basso',pt:'Baixo',nl:'Laag',pl:'Niskie',sv:'Lag',da:'Lav',fi:'Matala',el:'Chamilo',cs:'Nizke',ro:'Scazut',hu:'Alacsony',ca:'Baix',ru:'Nizkij',ar:'Munkhafid',ko:'Natda',zh:'Di',ja:'Hikui' },
  'agent.classification': { en:'Classification Agent',es:'Agente de Clasificacion',de:'Klassifizierungsagent',fr:'Agent de Classification',it:'Agente di Classificazione',pt:'Agente de Classificacao',nl:'Classificatieagent',pl:'Agent Klasyfikacji',sv:'Klassificeringsagent',da:'Klassificeringsagent',fi:'Luokitteluagentti',el:'Praktoreas Taxinomisis',cs:'Klasifikacni agent',ro:'Agent de clasificare',hu:'Osztalyozasi ugynok',ca:'Agent de Classificacio',ru:'Agent klassifikacii',ar:'Wakil al-tasnif',ko:'Bunryu ejenteu',zh:'Fenlei daili',ja:'Bunrui eejento' },
  'agent.technical_audit': { en:'Technical Audit Agent',es:'Agente de Auditoria Tecnica',de:'Technischer Prufagent',fr:"Agent d'Audit Technique",it:'Agente di Audit Tecnico',pt:'Agente de Auditoria Tecnica',nl:'Technische Auditinagent',pl:'Agent Audytu Technicznego',sv:'Teknisk granskningsagent',da:'Teknisk revisionsagent',fi:'Teknisen tarkastuksen agentti',el:'Praktoreas Technikou Elegchou',cs:'Agent technickeho auditu',ro:'Agent de audit tehnic',hu:'Technikai audit ugynok',ca:'Agent d\'Auditoria Tecnica',ru:'Agent tekhnicheskogo audita',ar:'Wakil al-tadqiq al-fanni',ko:'Gisul gamsa ejenteu',zh:'Jishu shenji daili',ja:'Gijutsu kansa eejento' },
  'agent.bias_detection': { en:'Bias Detection Agent',es:'Agente de Deteccion de Sesgo',de:'Bias-Erkennungsagent',fr:'Agent de Detection de Biais',it:'Agente di Rilevamento Bias',pt:'Agente de Deteccao de Vies',nl:'Bias-detectieagent',pl:'Agent Wykrywania Stronniczosci',sv:'Agent for partiskhetsdetektion',da:'Bias-detektionsagent',fi:'Harhan tunnistusagentti',el:'Praktoreas Anichneysis Prokatilipsis',cs:'Agent detekce zaujatosti',ro:'Agent de detectare bias',hu:'Elfogultsag felderito ugynok',ca:'Agent de Deteccio de Biaix',ru:'Agent obnaruzheniya predvzyatosti',ar:'Wakil kashf al-tahayuz',ko:'Pyeonhyang tamji ejenteu',zh:'Piancha jiance daili',ja:'Baiasu kenshutsu eejento' },
  'agent.documentation': { en:'Documentation Generator',es:'Generador de Documentacion',de:'Dokumentationsgenerator',fr:'Generateur de Documentation',it:'Generatore di Documentazione',pt:'Gerador de Documentacao',nl:'Documentatiegenerator',pl:'Generator Dokumentacji',sv:'Dokumentationsgenerator',da:'Dokumentationsgenerator',fi:'Dokumentaatiogeneraattori',el:'Gennitra Tekmerioseos',cs:'Generator dokumentace',ro:'Generator de documentatie',hu:'Dokumentacio generalo',ca:'Generador de Documentacio',ru:'Generator dokumentacii',ar:'Muwallid al-watha\'iq',ko:'Munseo saengseonggi',zh:'Wendan shengchengqi',ja:'Dokyumento jenereeta' },
  'agent.monitoring': { en:'Monitoring Agent',es:'Agente de Monitoreo',de:'Uberwachungsagent',fr:'Agent de Surveillance',it:'Agente di Monitoraggio',pt:'Agente de Monitorizacao',nl:'Monitoringagent',pl:'Agent Monitoringu',sv:'Overvakningsagent',da:'Overvagningsagent',fi:'Valvonta-agentti',el:'Praktoreas Parakolouthisis',cs:'Monitorovaci agent',ro:'Agent de monitorizare',hu:'Monitorozo ugynok',ca:'Agent de Monitoratge',ru:'Agent monitoringa',ar:'Wakil al-muraqaba',ko:'Monitoring ejenteu',zh:'Jiance daili',ja:'Monitaringu eejento' },
  'ui.dashboard': { en:'Dashboard',es:'Panel',de:'Dashboard',fr:'Tableau de bord',it:'Cruscotto',pt:'Painel',nl:'Dashboard',pl:'Panel',sv:'Instrumentpanel',da:'Dashboard',fi:'Kojelauta',el:'Pinakida',cs:'Hlavni panel',ro:'Tablou de bord',hu:'Iranyitopult',ca:'Tauler',ru:'Panel upravleniya',ar:'Lawhat al-tah\'akkum',ko:'Daesiboedeu',zh:'Yibiaopan',ja:'Dasshuboddo' },
  'ui.systems': { en:'AI Systems',es:'Sistemas de IA',de:'KI-Systeme',fr:"Systemes d'IA",it:'Sistemi IA',pt:'Sistemas de IA',nl:'AI-systemen',pl:'Systemy AI',sv:'AI-system',da:'AI-systemer',fi:'Tekoalyjarjestelmat',el:'Systimata AI',cs:'AI systemy',ro:'Sisteme IA',hu:'MI rendszerek',ca:'Sistemes d\'IA',ru:'Sistemy II',ar:'Anzimat al-dhaka\' al-istina\'i',ko:'AI siseutem',zh:'AI xitong',ja:'AI shisutemu' },
  'ui.findings': { en:'Findings',es:'Hallazgos',de:'Befunde',fr:'Constats',it:'Risultati',pt:'Descobertas',nl:'Bevindingen',pl:'Ustalenia',sv:'Resultat',da:'Resultater',fi:'Havainnot',el:'Evrimata',cs:'Nalezy',ro:'Constatari',hu:'Megallapitasok',ca:'Troballes',ru:'Rezul\'taty',ar:'Al-nata\'ij',ko:'Balgyeon',zh:'Faxian',ja:'Kekka' },
  'ui.documents': { en:'Documents',es:'Documentos',de:'Dokumente',fr:'Documents',it:'Documenti',pt:'Documentos',nl:'Documenten',pl:'Dokumenty',sv:'Dokument',da:'Dokumenter',fi:'Asiakirjat',el:'Engrafa',cs:'Dokumenty',ro:'Documente',hu:'Dokumentumok',ca:'Documents',ru:'Dokumenty',ar:'Al-watha\'iq',ko:'Munseo',zh:'Wendang',ja:'Dokyumento' },
  'ui.monitoring': { en:'Monitoring',es:'Monitoreo',de:'Uberwachung',fr:'Surveillance',it:'Monitoraggio',pt:'Monitorizacao',nl:'Monitoring',pl:'Monitoring',sv:'Overvakning',da:'Overvagning',fi:'Valvonta',el:'Parakolouthisi',cs:'Monitoring',ro:'Monitorizare',hu:'Monitorozas',ca:'Monitoratge',ru:'Monitoring',ar:'Al-muraqaba',ko:'Monitoring',zh:'Jiance',ja:'Monitaringu' },
  'ui.analytics': { en:'Analytics',es:'Analitica',de:'Analytik',fr:'Analytique',it:'Analisi',pt:'Analitica',nl:'Analyse',pl:'Analityka',sv:'Analys',da:'Analyse',fi:'Analytiikka',el:'Analytika',cs:'Analyza',ro:'Analitica',hu:'Elemzes',ca:'Analitica',ru:'Analitika',ar:'Al-tahlilat',ko:'Bunseok',zh:'Fenxi',ja:'Bunseki' },
  'ui.settings': { en:'Settings',es:'Ajustes',de:'Einstellungen',fr:'Parametres',it:'Impostazioni',pt:'Configuracoes',nl:'Instellingen',pl:'Ustawienia',sv:'Installningar',da:'Indstillinger',fi:'Asetukset',el:'Rythmiseis',cs:'Nastaveni',ro:'Setari',hu:'Beallitasok',ca:'Configuracio',ru:'Nastrojki',ar:'Al-i\'dadat',ko:'Seoljjeong',zh:'Shezhi',ja:'Settei' },
  'ui.assistant': { en:'Compliance Assistant',es:'Asistente de Cumplimiento',de:'Konformitatsassistent',fr:'Assistant Conformite',it:'Assistente Conformita',pt:'Assistente de Conformidade',nl:'Compliance Assistent',pl:'Asystent Zgodnosci',sv:'Kompliansassistent',da:'Compliance-assistent',fi:'Vaatimustenmukaisuusavustaja',el:'Voithos Symmetochis',cs:'Asistent shody',ro:'Asistent de conformitate',hu:'Megfelelosegi asszisztens',ca:'Assistent de Compliment',ru:'Pomoshchnik po sootvetstviyu',ar:'Musa\'id al-imtithal',ko:'Junsu bojowan',zh:'Heguixing zhushou',ja:'Konpuraiansu ashisutanto' },
  'ui.roadmap': { en:'Compliance Roadmap',es:'Hoja de Ruta',de:'Compliance-Roadmap',fr:'Feuille de Route',it:'Tabella di Marcia',pt:'Roteiro',nl:'Compliance Routekaart',pl:'Plan Zgodnosci',sv:'Kompliansplan',da:'Compliance-plan',fi:'Vaatimustenmukaisuussuunnitelma',el:'Chartis Symmetochis',cs:'Plan shody',ro:'Foaie de parcurs',hu:'Megfelelosegi uterv',ca:'Full de Ruta',ru:'Dorozhnaya karta',ar:'Kharitat al-tariq',ko:'Junsu romaep',zh:'Heguixing luxiantu',ja:'Konpuraiansu rodomapu' },
  'ui.incidents': { en:'Incidents',es:'Incidentes',de:'Vorfalle',fr:'Incidents',it:'Incidenti',pt:'Incidentes',nl:'Incidenten',pl:'Incydenty',sv:'Incidenter',da:'Haendelser',fi:'Tapahtumat',el:'Symvanta',cs:'Incidenty',ro:'Incidente',hu:'Incidensek',ca:'Incidents',ru:'Incidenty',ar:'Al-hawadith',ko:'Sageon',zh:'Shijian',ja:'Inshidento' },
  'ui.exports': { en:'Export',es:'Exportar',de:'Export',fr:'Exporter',it:'Esporta',pt:'Exportar',nl:'Exporteren',pl:'Eksport',sv:'Exportera',da:'Eksporter',fi:'Vienti',el:'Exagogi',cs:'Export',ro:'Export',hu:'Exportalas',ca:'Exportar',ru:'Eksport',ar:'Tasdir',ko:'Naebonaegi',zh:'Daochu',ja:'Ekusupooto' },
  'action.run_assessment': { en:'Run Assessment',es:'Ejecutar evaluacion',de:'Bewertung starten',fr:'Lancer evaluation',it:'Esegui valutazione',pt:'Executar avaliacao',nl:'Beoordeling starten',pl:'Uruchom ocene',sv:'Kor bedomning',da:'Kor vurdering',fi:'Suorita arviointi',el:'Ektelesi axiologisis',cs:'Spustit hodnoceni',ro:'Ruleaza evaluarea',hu:'Ertekeles futtatasa',ca:'Executar avaluacio',ru:'Zapustit\' ocenku',ar:'Tashghil al-taqyim',ko:'Pyeongga silhaeng',zh:'Yunxing pinggu',ja:'Hyouka wo jikkou' },
  'action.generate_doc': { en:'Generate Documentation',es:'Generar documentacion',de:'Dokumentation erstellen',fr:'Generer documentation',it:'Genera documentazione',pt:'Gerar documentacao',nl:'Documentatie genereren',pl:'Generuj dokumentacje',sv:'Generera dokumentation',da:'Generer dokumentation',fi:'Luo dokumentaatio',el:'Dimiourgia tekmerioseos',cs:'Generovat dokumentaci',ro:'Genereaza documentatia',hu:'Dokumentacio generalasa',ca:'Generar documentacio',ru:'Sgenerirovat\' dokumentaciyu',ar:'Tawlid al-watha\'iq',ko:'Munseo saengseong',zh:'Shengcheng wendang',ja:'Dokyumento wo sakusei' },
  'action.register_system': { en:'Register System',es:'Registrar sistema',de:'System registrieren',fr:'Enregistrer systeme',it:'Registra sistema',pt:'Registrar sistema',nl:'Systeem registreren',pl:'Zarejestruj system',sv:'Registrera system',da:'Registrer system',fi:'Rekisteroi jarjestelma',el:'Katagraphi systimatos',cs:'Registrovat system',ro:'Inregistreaza sistemul',hu:'Rendszer regisztralasa',ca:'Registrar sistema',ru:'Zaregistrirovat\' sistemu',ar:'Tasjil al-nizam',ko:'Siseutem deungnok',zh:'Zhuce xitong',ja:'Shisutemu touroku' },
  'article.art5': { en:'Art. 5: Prohibited practices',es:'Art. 5: Practicas prohibidas',de:'Art. 5: Verbotene Praktiken',fr:'Art. 5: Pratiques interdites',it:'Art. 5: Pratiche vietate',pt:'Art. 5: Praticas proibidas',nl:'Art. 5: Verboden praktijken',pl:'Art. 5: Zakazane praktyki',sv:'Art. 5: Forbjudna metoder',da:'Art. 5: Forbudte praksisser',fi:'Art. 5: Kielletyt kaytannot',el:'Art. 5: Apagoreumenes praktikes',cs:'Cl. 5: Zakazane praktiky',ro:'Art. 5: Practici interzise',hu:'5. cikk: Tiltott gyakorlatok',ca:'Art. 5: Practiques prohibides',ru:'St. 5: Zapreshchennye praktiki',ar:'Al-madda 5: Al-mumarasat al-mahzura',ko:'Je5jo: Geumji gwanhaeng',zh:'Di5tiao: Jinzhi zuofa',ja:'Dai5jou: Kinshi koui' },
  'article.art9': { en:'Art. 9: Risk management',es:'Art. 9: Gestion de riesgos',de:'Art. 9: Risikomanagement',fr:'Art. 9: Gestion des risques',it:'Art. 9: Gestione rischio',pt:'Art. 9: Gestao de riscos',nl:'Art. 9: Risicobeheer',pl:'Art. 9: Zarzadzanie ryzykiem',sv:'Art. 9: Riskhantering',da:'Art. 9: Risikostyring',fi:'Art. 9: Riskienhallinta',el:'Art. 9: Diacheirisi kindynou',cs:'Cl. 9: Rizeni rizik',ro:'Art. 9: Managementul riscurilor',hu:'9. cikk: Kockazatkezeles',ca:'Art. 9: Gestio de riscos',ru:'St. 9: Upravlenie riskami',ar:'Al-madda 9: Idarat al-makhater',ko:'Je9jo: Wiheom gwanli',zh:'Di9tiao: Fengxian guanli',ja:'Dai9jou: Risuku kanri' },
  'article.art10': { en:'Art. 10: Data governance',es:'Art. 10: Gobernanza de datos',de:'Art. 10: Datenverwaltung',fr:'Art. 10: Gouvernance donnees',it:'Art. 10: Governance dati',pt:'Art. 10: Governanca dados',nl:'Art. 10: Datagovernance',pl:'Art. 10: Zarzadzanie danymi',sv:'Art. 10: Datastyrning',da:'Art. 10: Datastyring',fi:'Art. 10: Tiedonhallinta',el:'Art. 10: Diakyvernisi dedomenon',cs:'Cl. 10: Sprava dat',ro:'Art. 10: Guvernanta datelor',hu:'10. cikk: Adatkormanyzas',ca:'Art. 10: Governanca de dades',ru:'St. 10: Upravlenie dannymi',ar:'Al-madda 10: Hawkamat al-bayanat',ko:'Je10jo: Deiteo geobeoneons',zh:'Di10tiao: Shuju zhili',ja:'Dai10jou: Deeta gabanansu' },
  'article.art11': { en:'Art. 11: Technical documentation',es:'Art. 11: Documentacion tecnica',de:'Art. 11: Technische Dokumentation',fr:'Art. 11: Documentation technique',it:'Art. 11: Documentazione tecnica',pt:'Art. 11: Documentacao tecnica',nl:'Art. 11: Technische documentatie',pl:'Art. 11: Dokumentacja techniczna',sv:'Art. 11: Teknisk dokumentation',da:'Art. 11: Teknisk dokumentation',fi:'Art. 11: Tekninen dokumentaatio',el:'Art. 11: Techniki tekmeriosi',cs:'Cl. 11: Technicka dokumentace',ro:'Art. 11: Documentatie tehnica',hu:'11. cikk: Muszaki dokumentacio',ca:'Art. 11: Documentacio tecnica',ru:'St. 11: Tekhnicheskaya dokumentaciya',ar:'Al-madda 11: Al-wathiqa al-fanniyya',ko:'Je11jo: Gisul munseo',zh:'Di11tiao: Jishu wendang',ja:'Dai11jou: Gijutsu bunsho' },
  'deadline.title': { en:'EU AI Act Enforcement Deadline',es:'Fecha limite EU AI Act',de:'EU-KI-Verordnung Durchsetzungsfrist',fr:"Date limite Reglement IA UE",it:'Scadenza regolamento IA UE',pt:'Prazo EU AI Act',nl:'EU AI Act handhavingsdeadline',pl:'Termin EU AI Act',sv:'EU AI Act deadline',da:'EU AI Act deadline',fi:'EU:n tekoalysaadoksen maaraaika',el:'Prosthesmia EU AI Act',cs:'Termin EU AI Act',ro:'Termenul EU AI Act',hu:'EU AI Act hatarideje',ca:'Termini EU AI Act',ru:'Srok EU AI Act',ar:'Al-mawid al-niha\'i li-qanun al-dhaka\' al-istina\'i',ko:'EU AI beop gihal',zh:'EU AI fa qixian',ja:'EU AI hou shimekiri' },
  'deadline.days_left': { en:'days remaining',es:'dias restantes',de:'Tage verbleibend',fr:'jours restants',it:'giorni rimanenti',pt:'dias restantes',nl:'dagen resterend',pl:'dni pozostalo',sv:'dagar kvar',da:'dage tilbage',fi:'paivaa jaljella',el:'meres apomenoun',cs:'dnu zbyva',ro:'zile ramase',hu:'nap van hatra',ca:'dies restants',ru:'dnej ostalos\'',ar:'Al-ayyam al-mutabaqqiya',ko:'il namsda',zh:'tian shengyu',ja:'nichi nokori' },
};

@Injectable()
export class I18nService {
  t(key: string, locale: Locale = 'en'): string { return T[key]?.[locale] || T[key]?.['en'] || key; }
  getAll(locale: Locale = 'en'): Record<string, string> { return Object.entries(T).reduce((acc, [k, v]) => ({ ...acc, [k]: v[locale] || v['en'] || k }), {}); }
  getLocales(): Locale[] { return ['en','es','de','fr','it','pt','nl','pl','sv','da','fi','el','cs','ro','hu','ca','ru','ar','ko','zh','ja']; }
  getLocaleNames(): Record<string, string> { return { en:'English',es:'Espanol',de:'Deutsch',fr:'Francais',it:'Italiano',pt:'Portugues',nl:'Nederlands',pl:'Polski',sv:'Svenska',da:'Dansk',fi:'Suomi',el:'Ellinika',cs:'Cestina',ro:'Romana',hu:'Magyar',ca:'Catala',ru:'Russkij',ar:'Al-Arabiyya',ko:'Hangugeo',zh:'Zhongwen',ja:'Nihongo' }; }
  getPromptLocale(locale: Locale): string {
    const m: Record<string, string> = { en:'Respond in English.',es:'Responde en espanol.',de:'Antworte auf Deutsch.',fr:'Repondez en francais.',it:'Rispondi in italiano.',pt:'Responda em portugues.',nl:'Antwoord in het Nederlands.',pl:'Odpowiedz po polsku.',sv:'Svara pa svenska.',da:'Svar pa dansk.',fi:'Vastaa suomeksi.',el:'Apantiste sta ellinika.',cs:'Odpovezte cesky.',ro:'Raspundeti in romana.',hu:'Valaszoljon magyarul.',ca:'Respon en catala.',ru:'Otvechat\' po-russki.',ar:'Ajib bil-arabiyya.',ko:'Hangugeo-ro daedaphaseyo.',zh:'Qing yong zhongwen huida.',ja:'Nihongo de kotaete kudasai.' };
    return m[locale] || m.en;
  }
  getKeyCount(): number { return Object.keys(T).length; }
  getLocaleCount(): number { return this.getLocales().length; }
}

@Controller('i18n')
export class I18nController {
  constructor(private i: I18nService) {}
  @Get() @ApiOperation({ summary: 'Get translations for locale' }) getTranslations(@Query('locale') l?: string) { return this.i.getAll((l || 'en') as Locale); }
  @Get('locales') @ApiOperation({ summary: 'List all 23 supported locales' }) getLocales() { return { locales: this.i.getLocales(), names: this.i.getLocaleNames(), count: this.i.getLocaleCount() }; }
  @Get('stats') @ApiOperation({ summary: 'Translation statistics' }) getStats() { return { keys: this.i.getKeyCount(), locales: this.i.getLocaleCount(), totalTranslations: this.i.getKeyCount() * this.i.getLocaleCount() }; }
}

@Module({ controllers: [I18nController], providers: [I18nService], exports: [I18nService] })
export class I18nModule {}
