import { Controller, Get, Injectable, Logger, Module } from '@nestjs/common';
import { ApiOperation } from '@nestjs/swagger';
import { PrismaService, PrismaModule } from '../prisma/prisma.module';
import { JwtAuthGuard, CurrentUser } from '../common/index';

// GPAI obligations from Art. 51-56 + Annex XI/XII
const GPAI_PROVIDERS = [
  { name: 'OpenAI', models: ['GPT-4', 'GPT-4o', 'GPT-4o-mini', 'GPT-3.5', 'DALL-E', 'Whisper', 'o1', 'o3'], systemic: true, flopThreshold: true },
  { name: 'Anthropic', models: ['Claude 3.5', 'Claude 3', 'Claude Opus', 'Claude Sonnet', 'Claude Haiku'], systemic: true, flopThreshold: true },
  { name: 'Google', models: ['Gemini Pro', 'Gemini Ultra', 'Gemini Flash', 'PaLM 2', 'Imagen'], systemic: true, flopThreshold: true },
  { name: 'Meta', models: ['Llama 3', 'Llama 2', 'Llama 3.1', 'Llama 3.2'], systemic: false, flopThreshold: false },
  { name: 'Mistral', models: ['Mistral Large', 'Mistral Medium', 'Mistral Small', 'Mixtral', 'Codestral'], systemic: false, flopThreshold: false },
  { name: 'Cohere', models: ['Command R+', 'Command R', 'Embed'], systemic: false, flopThreshold: false },
  { name: 'Stability AI', models: ['Stable Diffusion', 'SDXL', 'Stable Video'], systemic: false, flopThreshold: false },
  { name: 'Hugging Face', models: ['Hosted inference API models'], systemic: false, flopThreshold: false },
];

const DEPLOYER_OBLIGATIONS = [
  { article: 'Art. 26(1)', title: 'Use according to instructions', description: 'Use the AI system in accordance with the instructions of use accompanying the system.', effort: 'LOW', category: 'OPERATIONAL' },
  { article: 'Art. 26(2)', title: 'Human oversight', description: 'Ensure human oversight by persons with adequate competence, training, and authority.', effort: 'MEDIUM', category: 'OPERATIONAL' },
  { article: 'Art. 26(5)', title: 'Monitor operation', description: 'Monitor the operation and inform the provider of any risks, incidents, or malfunctions.', effort: 'MEDIUM', category: 'MONITORING' },
  { article: 'Art. 26(6)', title: 'Keep logs', description: 'Keep logs automatically generated by the system for at least 6 months.', effort: 'LOW', category: 'TECHNICAL' },
  { article: 'Art. 26(7)', title: 'Inform employees', description: 'Inform workers and their representatives that they are subject to an AI system.', effort: 'LOW', category: 'TRANSPARENCY' },
  { article: 'Art. 50(1)', title: 'AI interaction disclosure', description: 'Inform persons that they are interacting with an AI system (unless obvious from context).', effort: 'LOW', category: 'TRANSPARENCY' },
  { article: 'Art. 50(2)', title: 'Content marking', description: 'Label AI-generated content (text, audio, image, video) as artificially generated or manipulated.', effort: 'MEDIUM', category: 'TRANSPARENCY' },
  { article: 'Art. 50(4)', title: 'Deep fake labelling', description: 'Label deep fakes clearly as artificially generated or manipulated content.', effort: 'MEDIUM', category: 'TRANSPARENCY' },
];

const PROVIDER_OBLIGATIONS = [
  { article: 'Art. 53(1)(a)', title: 'Technical documentation', description: 'Draw up and keep up-to-date the technical documentation of the GPAI model (Annex XI).', effort: 'HIGH', category: 'DOCUMENTATION' },
  { article: 'Art. 53(1)(b)', title: 'Downstream provider info', description: 'Provide information and documentation to downstream providers to enable compliance.', effort: 'MEDIUM', category: 'DOCUMENTATION' },
  { article: 'Art. 53(1)(c)', title: 'Copyright compliance', description: 'Put in place a policy to comply with Union copyright law (Directive 2019/790).', effort: 'MEDIUM', category: 'LEGAL' },
  { article: 'Art. 53(1)(d)', title: 'Training data summary', description: 'Draw up and make publicly available a sufficiently detailed summary of training data content.', effort: 'HIGH', category: 'TRANSPARENCY' },
  { article: 'Art. 55(1)(a)', title: 'Model evaluation (systemic)', description: 'Perform model evaluation including adversarial testing to identify and mitigate systemic risks.', effort: 'VERY_HIGH', category: 'SAFETY', systemicOnly: true },
  { article: 'Art. 55(1)(b)', title: 'Risk mitigation (systemic)', description: 'Assess and mitigate possible systemic risks at Union level.', effort: 'VERY_HIGH', category: 'SAFETY', systemicOnly: true },
  { article: 'Art. 55(1)(d)', title: 'Incident reporting (systemic)', description: 'Report serious incidents to AI Office and relevant national authorities without undue delay.', effort: 'HIGH', category: 'MONITORING', systemicOnly: true },
  { article: 'Art. 55(1)(e)', title: 'Cybersecurity (systemic)', description: 'Ensure adequate level of cybersecurity protection for the model and its infrastructure.', effort: 'HIGH', category: 'SECURITY', systemicOnly: true },
];

interface GpaiScan { provider: string; models: string[]; isDeployer: boolean; isProvider: boolean; isFineTuning: boolean; systemic: boolean; }

@Injectable()
export class GpaiService {
  private readonly logger = new Logger(GpaiService.name);
  constructor(private prisma: PrismaService) {}

  async detectForOrg(orgId: string): Promise<{ scans: GpaiScan[]; totalObligations: number; deployerObligations: typeof DEPLOYER_OBLIGATIONS; providerObligations: any[]; recommendations: string[] }> {
    const systems = await this.prisma.aiSystem.findMany({ where: { organizationId: orgId, deletedAt: null }, select: { id: true, name: true, description: true, purpose: true, sector: true } });
    const scans: GpaiScan[] = [];
    const recommendations: string[] = [];

    for (const sys of systems) {
      const text = `${sys.description} ${sys.purpose}`.toLowerCase();
      for (const gp of GPAI_PROVIDERS) {
        const found = gp.models.filter(m => text.includes(m.toLowerCase()));
        if (found.length > 0 || text.includes(gp.name.toLowerCase())) {
          scans.push({ provider: gp.name, models: found.length > 0 ? found : [gp.name + ' (detected)'], isDeployer: true, isProvider: false, isFineTuning: text.includes('fine-tun') || text.includes('finetun') || text.includes('train'), systemic: gp.systemic });
        }
      }
      // Check for generic API usage
      if (text.match(/api\s*(key|call|endpoint|integration)/i) && text.match(/ai|llm|gpt|claude|gemini|model/i)) {
        if (!scans.some(s => s.provider)) {
          scans.push({ provider: 'Unknown AI API', models: ['Detected API integration'], isDeployer: true, isProvider: false, isFineTuning: false, systemic: false });
        }
      }
    }

    // Determine obligations
    const isDeployer = scans.some(s => s.isDeployer);
    const isFineTuning = scans.some(s => s.isFineTuning);
    const usesSystemic = scans.some(s => s.systemic);

    const applicableDeployer = isDeployer ? DEPLOYER_OBLIGATIONS : [];
    const applicableProvider = isFineTuning ? PROVIDER_OBLIGATIONS.filter(o => !(o as any).systemicOnly || usesSystemic) : [];

    if (isDeployer) recommendations.push('You are a DEPLOYER of GPAI-powered systems. Art. 26 and Art. 50 obligations apply since August 2025.');
    if (isFineTuning) recommendations.push('You are fine-tuning models, which may make you a PROVIDER. Art. 53 obligations apply. Consult legal counsel.');
    if (usesSystemic) recommendations.push('You use models with systemic risk (>10^25 FLOPs). Enhanced obligations under Art. 55 may cascade to you as deployer.');
    if (!isDeployer && !isFineTuning) recommendations.push('No GPAI usage detected. If you use any AI API, add it to your system descriptions for accurate detection.');

    return { scans: [...new Map(scans.map(s => [s.provider, s])).values()], totalObligations: applicableDeployer.length + applicableProvider.length, deployerObligations: applicableDeployer, providerObligations: applicableProvider, recommendations };
  }

  getProviders() { return GPAI_PROVIDERS; }
  getObligations() { return { deployer: DEPLOYER_OBLIGATIONS, provider: PROVIDER_OBLIGATIONS }; }
}

@Controller('gpai')
export class GpaiController {
  constructor(private s: GpaiService) {}
  @Get('detect') @ApiOperation({ summary: 'Detect GPAI usage in your AI systems' }) detect(@CurrentUser('organizationId') o: string) { return this.s.detectForOrg(o); }
  @Get('providers') @ApiOperation({ summary: 'Known GPAI providers and models' }) providers() { return this.s.getProviders(); }
  @Get('obligations') @ApiOperation({ summary: 'GPAI obligations (deployer + provider)' }) obligations() { return this.s.getObligations(); }
}

@Module({ imports: [PrismaModule], controllers: [GpaiController], providers: [GpaiService], exports: [GpaiService] })
export class GpaiModule {}
