import { Response } from 'express';
import { Controller, Get, Injectable, Module, Param, ParseUUIDPipe, Res } from '@nestjs/common';
import { ApiOperation } from '@nestjs/swagger';
import { PrismaService, PrismaModule } from '../prisma/prisma.module';
import { JwtAuthGuard, RolesGuard, Roles, CurrentUser } from '../common/index';

const LEGAL_DISCLAIMER = 'DISCLAIMER: This document is generated by AgentOps AI compliance platform and is provided for informational purposes only. It does not constitute legal advice. Consult a qualified legal professional for compliance decisions. AgentOps is not a law firm and does not provide legal services.';

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generateExecutiveReport(orgId: string): Promise<string> {
    const [org, systems, findings, assessments, events] = await Promise.all([
      this.prisma.organization.findUnique({ where: { id: orgId } }),
      this.prisma.aiSystem.findMany({ where: { organizationId: orgId, deletedAt: null }, include: { findings: { where: { status: { in: ['OPEN', 'IN_PROGRESS'] } } } } }),
      this.prisma.complianceFinding.groupBy({ by: ['severity'], where: { organizationId: orgId, status: { in: ['OPEN', 'IN_PROGRESS'] } }, _count: true }),
      this.prisma.assessment.findMany({ where: { organizationId: orgId, status: 'COMPLETED' }, orderBy: { completedAt: 'desc' }, take: 10, include: { aiSystem: { select: { name: true } } } }),
      this.prisma.monitoringEvent.findMany({ where: { organizationId: orgId, acknowledged: false }, take: 10 }),
    ]);

    const critical = findings.find(g => g.severity === 'CRITICAL')?._count || 0;
    const high = findings.find(g => g.severity === 'HIGH')?._count || 0;
    const totalOpen = findings.reduce((s, g) => s + g._count, 0);
    const deadline = new Date('2026-08-02T00:00:00Z');
    const daysLeft = Math.ceil((deadline.getTime() - Date.now()) / 86400000);
    const compliant = systems.filter(s => s.complianceStatus === 'COMPLIANT').length;

    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>AgentOps Compliance Report - ${org?.name}</title>
<style>body{font-family:Arial,sans-serif;max-width:900px;margin:0 auto;padding:40px;color:#1a1a1a;line-height:1.6}
.header{border-bottom:3px solid #1e40af;padding-bottom:20px;margin-bottom:30px}h1{color:#1e40af;font-size:24px}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.stat{text-align:center;padding:16px;border:1px solid #e5e7eb;border-radius:8px}
.stat .val{font-size:28px;font-weight:700}.stat .lbl{font-size:11px;color:#6b7280;text-transform:uppercase}
.risk-high{color:#f97316}.risk-critical{color:#dc2626}.risk-ok{color:#10b981}.risk-warn{color:#f59e0b}
table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #e5e7eb}th{background:#f8fafc;font-size:12px;text-transform:uppercase;color:#6b7280}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:600}
.footer{margin-top:40px;padding-top:20px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af}
@media print{body{padding:20px}}</style></head><body>
<div class="header"><h1>Compliance Report</h1><p>${org?.name} | Generated: ${new Date().toISOString().split('T')[0]} | Regulation: EU AI Act (2024/1689)</p></div>

<h2>Executive Summary</h2>
<div class="grid">
  <div class="stat"><div class="val">${systems.length}</div><div class="lbl">AI Systems</div></div>
  <div class="stat"><div class="val ${compliant === systems.length ? 'risk-ok' : 'risk-warn'}">${systems.length > 0 ? Math.round((compliant / systems.length) * 100) : 0}%</div><div class="lbl">Compliance Rate</div></div>
  <div class="stat"><div class="val ${critical > 0 ? 'risk-critical' : 'risk-ok'}">${totalOpen}</div><div class="lbl">Open Findings</div></div>
  <div class="stat"><div class="val ${daysLeft < 120 ? 'risk-critical' : 'risk-warn'}">${daysLeft}</div><div class="lbl">Days to Deadline</div></div>
</div>

<h2>AI Systems</h2>
<table><tr><th>System</th><th>Risk Level</th><th>Compliance</th><th>Open Findings</th></tr>
${systems.map(s => `<tr><td>${s.name} (v${s.version})</td><td><span class="badge" style="background:${s.riskLevel === 'HIGH' ? '#fef3c7' : s.riskLevel === 'LIMITED' ? '#fef9c3' : '#f0fdf4'}">${s.riskLevel || 'N/A'}</span></td><td><span class="badge" style="background:${s.complianceStatus === 'COMPLIANT' ? '#d1fae5' : s.complianceStatus === 'PARTIAL' ? '#fef3c7' : '#fee2e2'}">${s.complianceStatus}</span></td><td>${s.findings.length}</td></tr>`).join('')}
</table>

${critical > 0 ? `<h2 style="color:#dc2626">Critical Findings Requiring Immediate Action</h2><p>There are <strong>${critical} critical</strong> and <strong>${high} high</strong> severity findings that must be addressed before the August 2, 2026 deadline.</p>` : ''}

<h2>Recent Assessments</h2>
<table><tr><th>Date</th><th>System</th><th>Score</th><th>Status</th></tr>
${assessments.map(a => `<tr><td>${a.completedAt?.toISOString().split('T')[0]}</td><td>${a.aiSystem?.name}</td><td>${a.overallScore || 'N/A'}/100</td><td>${a.status}</td></tr>`).join('')}
</table>

${events.length > 0 ? `<h2>Active Monitoring Alerts</h2><table><tr><th>Severity</th><th>Alert</th><th>Date</th></tr>${events.map(e => `<tr><td><span class="badge" style="background:${e.severity === 'CRITICAL' ? '#fee2e2' : '#fef3c7'}">${e.severity}</span></td><td>${e.title}</td><td>${e.createdAt.toISOString().split('T')[0]}</td></tr>`).join('')}</table>` : ''}

<h2>Recommendations</h2>
<ol>
${critical > 0 ? '<li><strong>Address all CRITICAL findings immediately.</strong> These represent potential violations of the EU AI Act with penalties up to 35M EUR or 7% of global revenue.</li>' : ''}
${systems.some(s => s.complianceStatus === 'NON_COMPLIANT') ? '<li>Run compliance assessments on all NON_COMPLIANT systems and implement remediation actions.</li>' : ''}
${systems.some(s => !s.riskLevel) ? '<li>Classify all unassessed AI systems to determine their risk level and applicable obligations.</li>' : ''}
<li>Schedule regular re-assessments (at least quarterly) per Article 9 continuous risk management requirements.</li>
<li>Generate and maintain Annex IV technical documentation for all HIGH risk systems.</li>
</ol>

<div class="footer"><p>Generated by AgentOps Compliance Platform | This report should be reviewed by qualified compliance personnel.</p></div>
</body></html>`;
  }

  async generateSystemReport(orgId: string, systemId: string): Promise<string> {
    const system = await this.prisma.aiSystem.findFirst({
      where: { id: systemId, organizationId: orgId, deletedAt: null },
      include: {
        assessments: { where: { status: 'COMPLETED' }, orderBy: { completedAt: 'desc' }, take: 5, include: { results: true } },
        findings: { orderBy: [{ severity: 'asc' }, { createdAt: 'desc' }] },
        documents: { orderBy: { createdAt: 'desc' } },
      },
    });
    if (!system) return '<h1>System not found</h1>';

    const openFindings = system.findings.filter(f => ['OPEN', 'IN_PROGRESS'].includes(f.status));

    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>System Report - ${system.name}</title>
<style>body{font-family:Arial;max-width:900px;margin:0 auto;padding:40px;color:#1a1a1a;line-height:1.6}.header{border-bottom:3px solid #1e40af;padding-bottom:20px}h1{color:#1e40af}
table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #e5e7eb}th{background:#f8fafc;font-size:12px;text-transform:uppercase;color:#6b7280}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:600}
.footer{margin-top:40px;border-top:1px solid #e5e7eb;padding-top:20px;font-size:11px;color:#9ca3af}</style></head><body>
<div class="header"><h1>${system.name} - Compliance Report</h1><p>Version: ${system.version} | Risk Level: ${system.riskLevel || 'Not classified'} | Status: ${system.complianceStatus} | Generated: ${new Date().toISOString().split('T')[0]}</p></div>

<h2>System Information</h2>
<table>
<tr><td><strong>Description</strong></td><td>${system.description}</td></tr>
<tr><td><strong>Purpose</strong></td><td>${system.purpose || 'Not specified'}</td></tr>
<tr><td><strong>Sector</strong></td><td>${system.sector || 'Not specified'}</td></tr>
<tr><td><strong>Data Types</strong></td><td>${system.dataTypes?.join(', ') || 'Not specified'}</td></tr>
<tr><td><strong>Affected Population</strong></td><td>${system.affectedPopulation || 'Not specified'}</td></tr>
</table>

<h2>Open Findings (${openFindings.length})</h2>
<table><tr><th>Severity</th><th>Article</th><th>Title</th><th>Status</th><th>Effort</th></tr>
${openFindings.map(f => `<tr><td><span class="badge" style="background:${f.severity === 'CRITICAL' ? '#fee2e2' : f.severity === 'HIGH' ? '#ffedd5' : '#fef9c3'}">${f.severity}</span></td><td>${f.articleRef}</td><td>${f.title}</td><td>${f.status}</td><td>${f.estimatedEffort}</td></tr>`).join('')}
</table>

<h2>Assessment History</h2>
<table><tr><th>Date</th><th>Type</th><th>Score</th><th>Agents</th></tr>
${system.assessments.map(a => `<tr><td>${a.completedAt?.toISOString().split('T')[0]}</td><td>${a.type}</td><td>${a.overallScore || 'N/A'}/100</td><td>${a.results?.map(r => `${r.agentType}: ${r.score != null ? Math.round(r.score as number) : '-'}`).join(', ')}</td></tr>`).join('')}
</table>

<h2>Generated Documents</h2>
<table><tr><th>Document</th><th>Version</th><th>Generated</th></tr>
${system.documents.map(d => `<tr><td>${d.title}</td><td>v${d.version}</td><td>${d.createdAt.toISOString().split('T')[0]}</td></tr>`).join('')}
${system.documents.length === 0 ? '<tr><td colspan="3">No documents generated yet. Generate Annex IV documentation for compliance.</td></tr>' : ''}
</table>

<div class="footer"><p>Generated by AgentOps | EU AI Act (Regulation 2024/1689)</p></div></body></html>`;
  }
}

@Controller('reports')
export class ReportsController {
  constructor(private s: ReportsService) {}

  @Get('executive') @ApiOperation({ summary: 'Generate executive compliance report' })
  async executive(@CurrentUser('organizationId') o: string, @Res() res: Response) {
    const html = await this.s.generateExecutiveReport(o);
    res.set({ 'Content-Type': 'text/html', 'Content-Disposition': `attachment; filename="agentops-report-${new Date().toISOString().split('T')[0]}.html"` });
    res.send(html);
  }

  @Get('system/:id') @ApiOperation({ summary: 'System' })
  async system(@Param('id', ParseUUIDPipe) id: string, @CurrentUser('organizationId') o: string, @Res() res: Response) {
    const html = await this.s.generateSystemReport(o, id);
    res.set({ 'Content-Type': 'text/html', 'Content-Disposition': `attachment; filename="system-report-${id.substring(0, 8)}.html"` });
    res.send(html);
  }
}

@Module({ imports: [PrismaModule], controllers: [ReportsController], providers: [ReportsService] })
export class ReportsModule {}
