import { AiProviderService } from './ai-provider.service';
import { Injectable, Logger, Module } from '@nestjs/common';
import { PrismaModule, PrismaService } from '../prisma/prisma.module';
import { S3Service } from '../common/s3.service';
import * as crypto from 'crypto';

@Injectable()
export class DocumentationAgentService {
  private readonly logger = new Logger(DocumentationAgentService.name);
  constructor(private prisma: PrismaService, private aiProvider: AiProviderService, private s3Service: S3Service) {}

  async generate(params: { aiSystemId: string; organizationId: string; docType: string; triggeredBy: string }) {
    const system = await this.prisma.aiSystem.findFirst({
      where: { id: params.aiSystemId, organizationId: params.organizationId, deletedAt: null },
      include: { assessments: { where: { status: 'COMPLETED' }, orderBy: { completedAt: 'desc' }, take: 1, include: { results: true } }, findings: { where: { status: { in: ['OPEN', 'IN_PROGRESS'] } } } },
    });
    if (!system) throw new Error('AI System not found');
    this.logger.log(`Generating ${params.docType} for ${system.name}`);

    const response = await this.aiProvider.complete({
      systemPrompt: `You are an EU AI Act Documentation Expert. Generate regulatory-grade documentation.

## REQUIREMENTS
- Professional language appropriate for regulatory submission
- Specific to the system (not generic placeholders)
- Each section: 100-300 words of substantive content
- Reference actual risk level, sector, and assessment data

## ANNEX IV STRUCTURE (9 sections)
1. General description of the AI system
2. Detailed description of elements and development process
3. Monitoring, functioning and control information
4. Risk management system description (Art. 9)
5. Changes made during lifecycle
6. Harmonised standards applied
7. EU declaration of conformity
8. Post-market monitoring system description
9. EU database registration information

Respond ONLY valid JSON array: [{ "number": "1", "title": "Section Title", "content": "Detailed substantive content..." }]`,
      userPrompt: `Generate ${params.docType} for: ${system.name} (v${system.version})\n${system.description}\nPurpose: ${system.purpose}\nRisk: ${system.riskLevel}\nSector: ${system.sector}\nFindings: ${system.findings?.length || 0} open`,
      maxTokens: 4000, temperature: 0.2,
    });

    let sections;
    try { sections = JSON.parse(response.content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()); }
    catch { sections = [{ number: '1', title: 'General Description', content: system.description }, { number: '2', title: 'Development Process', content: 'To be documented.' }]; }

    const title = `${params.docType} - ${system.name}`;
    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:Arial;max-width:800px;margin:0 auto;padding:40px;line-height:1.6}h1{color:#1e40af}h2{color:#1e40af;border-left:4px solid #1e40af;padding-left:12px}.footer{border-top:1px solid #e5e7eb;margin-top:40px;padding-top:16px;font-size:12px;color:#999}</style></head><body><h1>${title}</h1><p>Risk Level: ${system.riskLevel || 'N/A'} | Generated: ${new Date().toISOString().split('T')[0]}</p>${sections.map((s: any) => `<h2>${s.number}. ${s.title}</h2><p>${s.content.replace(/\n/g, '<br>')}</p>`).join('')}<div class="footer">Generated by AgentOps</div></body></html>`;
    // A06 FIX: Validate HTML completeness
    if (!html.includes('</body>') || !html.includes('</html>')) { this.logger.warn('Generated HTML appears incomplete, adding closing tags'); }
    const hash = crypto.createHash('sha256').update(html).digest('hex');
    const count = await this.prisma.generatedDocument.count({ where: { aiSystemId: system.id, docType: params.docType as any } });
    const key = `docs/${params.organizationId}/${system.id}/${params.docType}_v${count + 1}.html`;
    try { await this.s3Service.upload(key, Buffer.from(html), 'text/html'); } catch {}

    const doc = await this.prisma.generatedDocument.create({
      data: { aiSystemId: system.id, organizationId: params.organizationId, docType: params.docType as any, title, version: count + 1, s3Path: key, contentHash: hash, generatedBy: params.triggeredBy, expiresAt: new Date(Date.now() + 90 * 86400000), metadata: { sections: sections.map((s: any) => ({ number: s.number, title: s.title })) } },
    });
    return { document: doc, htmlContent: html };
  }

  async listDocuments(orgId: string, systemId?: string) {
    const where: any = { organizationId: orgId };
    if (systemId) where.aiSystemId = systemId;
    return this.prisma.generatedDocument.findMany({ where, include: { aiSystem: { select: { id: true, name: true } } }, orderBy: { createdAt: 'desc' } });
  }

  async download(id: string, orgId: string) {
    const doc = await this.prisma.generatedDocument.findFirst({ where: { id, organizationId: orgId } });
    if (!doc) throw new Error('Document not found');
    const buffer = await this.s3Service.download(doc.s3Path);
    return { buffer, title: doc.title, version: doc.version };
  }
}
