import { Response } from 'express';
import { Controller, Get, Injectable, Logger, Module, Param, ParseUUIDPipe, Post, Query, Res } from '@nestjs/common';
import { ApiOperation } from '@nestjs/swagger';
import { PrismaService, PrismaModule } from '../prisma/prisma.module';
import { JwtAuthGuard, RolesGuard, Roles, CurrentUser } from '../common/index';
import { AgentsModule, DocumentationAgentService } from '../agents/agents.module';

// B04 FIX: Proper service layer separating business logic from controller
const LEGAL_DISCLAIMER = 'DISCLAIMER: This document is generated by AgentOps AI compliance platform and is provided for informational purposes only. It does not constitute legal advice. Consult a qualified legal professional for compliance decisions. AgentOps is not a law firm and does not provide legal services.';

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name);
  constructor(private prisma: PrismaService, private docAgent: DocumentationAgentService) {}
  async list(orgId: string, aiSystemId?: string) {
    const where: any = { organizationId: orgId };
    if (aiSystemId) where.aiSystemId = aiSystemId;
    return this.prisma.generatedDocument.findMany({ where, orderBy: { createdAt: 'desc' }, take: 100, include: { aiSystem: { select: { name: true } } } });
  }
  async getById(id: string, orgId: string) {
    return this.prisma.generatedDocument.findFirst({ where: { id, organizationId: orgId } });
  }
  async download(id: string, orgId: string) {
    return this.docAgent.download(id, orgId);
  }
  async generate(params: { aiSystemId: string; organizationId: string; docType: string; triggeredBy: string }) {
    this.logger.log(`Generating ${params.docType} for system ${params.aiSystemId}`);
    return this.docAgent.generate(params);
  }
  async getStats(orgId: string) {
    const docs = await this.prisma.generatedDocument.groupBy({ by: ['docType'], where: { organizationId: orgId }, _count: true });
    return { total: docs.reduce((s, d) => s + d._count, 0), byType: docs.reduce((acc, d) => ({ ...acc, [d.docType]: d._count }), {}) };
  }
}
@Controller('documents')
export class DocumentsController {
  constructor(private s: DocumentsService) {}
  @Get() @ApiOperation({ summary: 'List documents' })
  list(@CurrentUser('organizationId') o: string, @Query('aiSystemId') sid?: string) { return this.s.list(o, sid); }
  @Get('stats') @ApiOperation({ summary: 'Document statistics' })
  stats(@CurrentUser('organizationId') o: string) { return this.s.getStats(o); }
  @Get(':id/download') @ApiOperation({ summary: 'Download document' })
  async download(@Param('id', ParseUUIDPipe) id: string, @CurrentUser('organizationId') o: string, @Res() res: Response) {
    const { buffer, title, version } = await this.s.download(id, o);
    res.set({ 'Content-Type': 'text/html', 'Content-Disposition': `attachment; filename="${title.replace(/\s/g, '_')}_v${version}.html"`, 'Content-Length': buffer.length });
    res.send(buffer);
  }
  @Post('generate/annex-iv/:systemId') @Roles('OWNER', 'ADMIN', 'COMPLIANCE_OFFICER') @ApiOperation({ summary: 'Gen annex i v' })
  genAnnexIV(@Param('systemId', ParseUUIDPipe) sid: string, @CurrentUser('organizationId') o: string, @CurrentUser('id') u: string) { return this.s.generate({ aiSystemId: sid, organizationId: o, docType: 'ANNEX_IV', triggeredBy: u }); }
  @Post('generate/fria/:systemId') @Roles('OWNER', 'ADMIN', 'COMPLIANCE_OFFICER') @ApiOperation({ summary: 'Gen f r i a' })
  genFRIA(@Param('systemId', ParseUUIDPipe) sid: string, @CurrentUser('organizationId') o: string, @CurrentUser('id') u: string) { return this.s.generate({ aiSystemId: sid, organizationId: o, docType: 'FRIA', triggeredBy: u }); }
  @Post('generate/conformity/:systemId') @Roles('OWNER', 'ADMIN') @ApiOperation({ summary: 'Gen conformity' })
  genConformity(@Param('systemId', ParseUUIDPipe) sid: string, @CurrentUser('organizationId') o: string, @CurrentUser('id') u: string) { return this.s.generate({ aiSystemId: sid, organizationId: o, docType: 'CONFORMITY_DECLARATION', triggeredBy: u }); }
  @Post('generate/transparency/:systemId') @Roles('OWNER', 'ADMIN', 'COMPLIANCE_OFFICER') @ApiOperation({ summary: 'Gen transparency' })
  genTransparency(@Param('systemId', ParseUUIDPipe) sid: string, @CurrentUser('organizationId') o: string, @CurrentUser('id') u: string) { return this.s.generate({ aiSystemId: sid, organizationId: o, docType: 'TRANSPARENCY_NOTICE', triggeredBy: u }); }
}
@Module({
  imports: [PrismaModule, AgentsModule],
  controllers: [DocumentsController],
  providers: [DocumentsService],
  exports: [DocumentsService],
})
export class DocumentsModule {}
